# Generated by Django 3.0.5 on 2020-05-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=60)),
                ('course_description', models.CharField(max_length=256)),
                ('credits', models.PositiveSmallIntegerField()),
                ('instructor', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
